services:
  pasteit:
    build: .
    image: milkyicedtea/pasteit
    container_name: pasteit
#    ports:
#      - "4000:4000"
    env_file:
      - .env
    # remove caddy_net in dev or if not needed
    networks:
      - pasteit_net
      - caddy_net

  postgres:
    image: postgres:18-bookworm
    container_name: pasteit-db
#    ports:
#      - "5432:5432"
    env_file:
      - .env
    networks:
      - pasteit_net
    volumes:
      - pasteit_pgdata:/var/lib/postgresql
      - ./dbinit:/docker-entrypoint-initdb.d

volumes:
  pasteit_pgdata:

# remove caddy_net in dev or if not needed
networks:
  caddy_net:
    external: true
  pasteit_net:
    driver: bridge