/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PasteIdRouteImport } from './routes/$pasteId'
import { Route as IndexRouteImport } from './routes/index'

const PasteIdRoute = PasteIdRouteImport.update({
  id: '/$pasteId',
  path: '/$pasteId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pasteId': typeof PasteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pasteId': typeof PasteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$pasteId': typeof PasteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$pasteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$pasteId'
  id: '__root__' | '/' | '/$pasteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PasteIdRoute: typeof PasteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$pasteId': {
      id: '/$pasteId'
      path: '/$pasteId'
      fullPath: '/$pasteId'
      preLoaderRoute: typeof PasteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PasteIdRoute: PasteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
